services:
  db:
    image: postgres:17
    container_name: databridge
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databridge
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d databridge"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
