"""initial tables

Revision ID: 23eef32bb1c8
Revises: 
Create Date: 2026-04-04 16:57:33.061873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23eef32bb1c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_operator', 'audit_logs', ['operator'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('default_output_format', sa.String(length=10), nullable=False),
    sa.Column('target_resource_type', sa.String(length=255), nullable=False),
    sa.Column('layout_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_report_templates_name', 'report_templates', ['name'], unique=False)
    op.create_index('ix_report_templates_report_type', 'report_templates', ['report_type'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_table', sa.String(length=255), nullable=False),
    sa.Column('column_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_templates_name', 'templates', ['name'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_created_at', 'import_jobs', ['created_at'], unique=False)
    op.create_index('ix_import_jobs_operator', 'import_jobs', ['operator'], unique=False)
    op.create_index('ix_import_jobs_status', 'import_jobs', ['status'], unique=False)
    op.create_index('ix_import_jobs_template_id', 'import_jobs', ['template_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('filter_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_jobs_created_at', 'report_jobs', ['created_at'], unique=False)
    op.create_index('ix_report_jobs_requested_by', 'report_jobs', ['requested_by'], unique=False)
    op.create_index('ix_report_jobs_status', 'report_jobs', ['status'], unique=False)
    op.create_index('ix_report_jobs_template_id', 'report_jobs', ['report_template_id'], unique=False)
    op.create_table('report_template_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_template_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('format_type', sa.String(length=20), nullable=False),
    sa.Column('format_pattern', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('aggregation', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['report_template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_template_id', 'field_key', name='uq_report_template_fields_key')
    )
    op.create_index('ix_report_template_fields_display_order', 'report_template_fields', ['report_template_id', 'display_order'], unique=False)
    op.create_index('ix_report_template_fields_template_id', 'report_template_fields', ['report_template_id'], unique=False)
    op.create_table('column_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_column', name='uq_column_mappings_job_source'),
    sa.UniqueConstraint('job_id', 'target_column', name='uq_column_mappings_job_target')
    )
    op.create_index('ix_column_mappings_job_id', 'column_mappings', ['job_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=20), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_errors_job_error_type', 'import_errors', ['job_id', 'error_type'], unique=False)
    op.create_index('ix_import_errors_job_id', 'import_errors', ['job_id'], unique=False)
    op.create_index('ix_import_errors_job_row', 'import_errors', ['job_id', 'row_number'], unique=False)
    op.create_table('report_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_job_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_job_id'], ['report_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_outputs_job_id', 'report_outputs', ['report_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_outputs_job_id', table_name='report_outputs')
    op.drop_table('report_outputs')
    op.drop_index('ix_import_errors_job_row', table_name='import_errors')
    op.drop_index('ix_import_errors_job_id', table_name='import_errors')
    op.drop_index('ix_import_errors_job_error_type', table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_column_mappings_job_id', table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index('ix_report_template_fields_template_id', table_name='report_template_fields')
    op.drop_index('ix_report_template_fields_display_order', table_name='report_template_fields')
    op.drop_table('report_template_fields')
    op.drop_index('ix_report_jobs_template_id', table_name='report_jobs')
    op.drop_index('ix_report_jobs_status', table_name='report_jobs')
    op.drop_index('ix_report_jobs_requested_by', table_name='report_jobs')
    op.drop_index('ix_report_jobs_created_at', table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index('ix_import_jobs_template_id', table_name='import_jobs')
    op.drop_index('ix_import_jobs_status', table_name='import_jobs')
    op.drop_index('ix_import_jobs_operator', table_name='import_jobs')
    op.drop_index('ix_import_jobs_created_at', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index('ix_templates_name', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_report_templates_report_type', table_name='report_templates')
    op.drop_index('ix_report_templates_name', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_operator', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
