#!/usr/bin/env bash
# sync-specs.sh — One-way sync from .kiro/specs/ to docs/specs/
# Source of truth: .kiro/specs/
# Target (read-only mirror): docs/specs/
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_DIR="$REPO_ROOT/.kiro/specs"
TARGET_DIR="$REPO_ROOT/docs/specs"

# Files to sync (edit this array to include/exclude files)
SYNC_FILES=("requirements.md" "design.md" "tasks.md" "INDEX.md")

HEADER_MARKER="<!-- AUTO-GENERATED: DO NOT EDIT -->"
HEADER_NOTICE="${HEADER_MARKER}
<!-- This file is a read-only mirror generated from .kiro/specs/. -->
<!-- Do not edit this file directly. Edit the source in .kiro/specs/ instead. -->
"

sync_file() {
  local src="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"

  local content
  content=$(cat "$src")

  # Write header + content, replacing any existing header
  {
    printf '%s\n' "$HEADER_NOTICE"
    # Strip existing header if present
    if echo "$content" | head -1 | grep -q "$HEADER_MARKER"; then
      # Skip lines until the first non-comment, non-empty line after the marker block
      echo "$content" | awk -v marker="$HEADER_MARKER" '
        BEGIN { skip=1 }
        skip && /^<!-- / { next }
        skip && /^$/ { next }
        { skip=0; print }
      '
    else
      echo "$content"
    fi
  } > "$dest"
}

main() {
  if [ ! -d "$SOURCE_DIR" ]; then
    echo "Source directory not found: $SOURCE_DIR" >&2
    exit 1
  fi

  local synced=0

  # Sync root INDEX.md
  if [ -f "$SOURCE_DIR/INDEX.md" ]; then
    sync_file "$SOURCE_DIR/INDEX.md" "$TARGET_DIR/INDEX.md"
    synced=$((synced + 1))
  fi

  for spec_dir in "$SOURCE_DIR"/*/; do
    [ -d "$spec_dir" ] || continue
    local spec_name
    spec_name=$(basename "$spec_dir")

    for filename in "${SYNC_FILES[@]}"; do
      local src="$spec_dir$filename"
      [ -f "$src" ] || continue

      local dest="$TARGET_DIR/$spec_name/$filename"
      sync_file "$src" "$dest"
      synced=$((synced + 1))
    done
  done

  echo "Synced $synced file(s) from .kiro/specs/ to docs/specs/"
}

main "$@"
